#!/bin/sh
# vim:sw=2 et

set -euo pipefail

if [ -n "${CI-}" ]; then
  exit 0
fi

PATH=`git rev-parse --show-toplevel`"/tools/bin:$PATH"


if ! which swiftformat > /dev/null; then
  echo "swiftformat not found"
  exit 0
fi

swiftformat "${SRCROOT}/${PRODUCT_NAME}"
